/*
2. Revenue by Category
Calculate total revenue generated by each product category.
*/

SELECT
    c.category_id,
    c.category_name,
    ROUND(CAST(SUM(oi.quantity * oi.price_per_unit) AS numeric), 2) AS total_sales_by_category,
    ROUND(
        CAST(
            SUM(oi.quantity * oi.price_per_unit) * 100.0 /
            (SELECT SUM(quantity * price_per_unit) FROM order_items)
        AS numeric), 2
    ) AS percent_contribution
FROM category c
JOIN products p 
    ON c.category_id = p.category_id
JOIN order_items oi
    ON oi.product_id = p.product_id
GROUP BY
    c.category_id, c.category_name
ORDER BY
    total_sales_by_category DESC;
